language: node_js
node_js: stable
sudo: false
env:
  global:
  - DISPLAY=:99.0
  - JPM_FIREFOX_BINARY=firefox
  - TMP_DIR=/tmp
before_install:
- sh -e /etc/init.d/xvfb start
before_script:
- npm install
- pwd
- cd $TMP_DIR
- mozilla-download --branch mozilla-central --product firefox $TMP_DIR
- cd $TRAVIS_BUILD_DIR
- export JPM_FIREFOX_BINARY=$TMP_DIR/firefox/firefox
script:
- npm test
notifications:
  email:
    on_failure: never
addons:
    code_climate:
        repo_token: 23c49e44a988bc403e15ee4ccf9d2ceaf2fa2ad743a3ce698140d63e42f2b06b
after_script:
  - codeclimate-test-reporter < lcov.info
