language: node_js
node_js:
  - "0.12"
env:
  global:
  - DISPLAY=:99.0
  - JPM_FIREFOX_BINARY=nightly
  - TMP_DIR=/tmp
before_install:
- sh -e /etc/init.d/xvfb start
#- sudo apt-get install firefox
before_script:
- npm install -g get-firefox
- git clone --depth=50 --branch=master git://github.com/mozilla/jpm.git mozilla/jpm $TMP_DIR/jpm
- cd $TMP_DIR/jpm
- npm link
- cd $TRAVIS_BUILD_DIR
script:
- jpm test -v -b $JPM_FIREFOX_BINARY
notifications:
  email:
    on_failure: never
