language: node_js
node_js:
  - "0.12"
env:
  global:
  - DISPLAY=:99.0
  - JPM_FIREFOX_BINARY=firefox
  - TMP_DIR=/tmp
before_install:
- sh -e /etc/init.d/xvfb start
before_script:
- npm install
- npm install -g jpm
- npm install -g mozilla-download
- pwd
- cd $TMP_DIR
- mozilla-download --branch mozilla-central --product firefox
- cd $TRAVIS_BUILD_DIR
- export JPM_FIREFOX_BINARY=$TMP_DIR/firefox/firefox
script:
- jpm test -v -b $JPM_FIREFOX_BINARY
notifications:
  email:
    on_failure: never
